# -*- coding: utf-8 -*-
"""Banking application .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNohyd3Xq0BSZMBRBw6V8PWDHqz6Wcpz
"""

class Account:
    def __init__(self, account_number, account_holder, balance=0.0):
        self.account_number = account_number
        self.account_holder = account_holder
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposited: ${amount:.2f}")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        if 0 < amount <= self.balance:
            self.balance -= amount
            print(f"Withdrew: ${amount:.2f}")
        else:
            print("Withdrawal amount must be positive and less than or equal to the balance.")

    def get_balance(self):
        return self.balance

class SavingsAccount(Account):
    def __init__(self, account_number, account_holder, balance=0.0, interest_rate=0.02):
        super().__init__(account_number, account_holder, balance)
        self.interest_rate = interest_rate

    def calculate_interest(self):
        interest = self.balance * self.interest_rate
        print(f"Calculated Interest: ${interest:.2f}")
        return interest

if __name__ == "__main__":
    # Create an instance of SavingsAccount
    savings_account = SavingsAccount("12345", "John Doe", 1000.0, 0.03)

    # Display initial account details
    print(f"Account Holder: {savings_account.account_holder}")
    print(f"Account Number: {savings_account.account_number}")
    print(f"Initial Balance: ${savings_account.get_balance():.2f}")

    # Perform a deposit
    savings_account.deposit(500)
    print(f"Balance after deposit: ${savings_account.get_balance():.2f}")

    # Perform a withdrawal
    savings_account.withdraw(300)
    print(f"Balance after withdrawal: ${savings_account.get_balance():.2f}")

    # Calculate interest
    interest = savings_account.calculate_interest()
    print(f"Interest earned: ${interest:.2f}")

    # Display final balance
    final_balance = savings_account.get_balance() + interest
    print(f"Final Balance: ${final_balance:.2f}")